import "server-only";
import { drizzleAdapter } from "better-auth/adapters/drizzle";
import { betterAuth } from "better-auth";
import { nextCookies } from "better-auth/next-js";
import { db } from "@/server/db";
import * as schema from "@/server/db/schema";
import { env } from "@/server/env";

export const auth = betterAuth({
  secret: env.BETTER_AUTH_SECRET,
  baseURL: env.BETTER_AUTH_URL,
  // Better Auth stores users/sessions/accounts in OUR Postgres via Drizzle
  database: drizzleAdapter(db, {
    provider: "pg",
    schema,
    usePlural: true, // our tables are "users", "sessions"... (not "user", "session")
  }),
  advanced: {
    // ids are generated by Postgres (integer identity), like in the rest of our schema
    database: { generateId: "serial" },
  },
  emailAndPassword: {
    enabled: true,
    // Nobody can register from outside: a user must belong to an organization.
    // Users are created by seed now (later: invitations)
    disableSignUp: true,
  },
  user: {
    // Our own columns in `users`. We tell Better Auth about them so its schema check passes.
    // input: false -> a client can NEVER set them (no "sign up as owner of org 1")
    additionalFields: {
      organizationId: { type: "number", required: true, input: false },
      role: {
        type: ["owner", "admin", "developer", "readonly"],
        required: false,
        defaultValue: "developer",
        input: false,
      },
    },
  },
  // Must be the LAST plugin: lets Server Actions set the session cookie
  plugins: [nextCookies()],
});
